import "./entry";

const html = `<div class="slate-editor group/editor relative w-full cursor-text overflow-x-hidden wrap-break-word whitespace-pre-wrap select-text rounded-md ring-offset-background focus-visible:outline-none placeholder:text-muted-foreground/80 **:data-slate-placeholder:top-[auto_!important] **:data-slate-placeholder:text-muted-foreground/80 **:data-slate-placeholder:opacity-100! [&_strong]:font-bold" data-slate-editor="true" data-slate-node="value" style="padding:0 calc(50% - 350px)"><h1 data-slate-node="element" data-block-id="vAzczav4gZ" data-slate-type="h1" data-slate-id="vAzczav4gZ" class="slate-h1 relative mb-1 mt-[1.6em] pb-1 font-heading text-4xl font-bold" style="position:relative"><span data-slate-node="text"><span data-slate-leaf="true"><span data-slate-string="true">Welcome to the Plate Playground!</span></span></span></h1><div data-slate-node="element" data-block-id="3PMYQQC5y1" data-slate-type="p" data-slate-id="3PMYQQC5y1" class="slate-p m-0 px-0 py-1" style="position:relative"><span data-slate-node="text"><span data-slate-leaf="true"><span data-slate-string="true">Experience a modern rich-text editor built with </span></span></span><a data-slate-node="element" data-slate-inline="true" href="https://slatejs.org/" data-slate-type="a" data-slate-url="https://slatejs.org" data-slate-id="eUUjncTvDo" class="slate-a font-medium text-primary underline decoration-primary underline-offset-4" style="position:relative"><span data-slate-node="text"><span data-slate-leaf="true"><span data-slate-string="true">Slate</span></span></span></a><span data-slate-node="text"><span data-slate-leaf="true"><span data-slate-string="true"> and </span></span></span><a data-slate-node="element" data-slate-inline="true" href="https://reactjs.org/" data-slate-type="a" data-slate-url="https://reactjs.org" data-slate-id="_jb2r2JWev" class="slate-a font-medium text-primary underline decoration-primary underline-offset-4" style="position:relative"><span data-slate-node="text"><span data-slate-leaf="true"><span data-slate-string="true">React</span></span></span></a><span data-slate-node="text"><span data-slate-leaf="true"><span data-slate-string="true">. This playground showcases just a part of Plate's capabilities. </span></span></span><a data-slate-node="element" data-slate-inline="true" href="/docs" data-slate-type="a" data-slate-url="/docs" data-slate-id="_P_i-qn9fy" class="slate-a font-medium text-primary underline decoration-primary underline-offset-4" style="position:relative"><span data-slate-node="text"><span data-slate-leaf="true"><span data-slate-string="true">Explore the documentation</span></span></span></a><span data-slate-node="text"><span data-slate-leaf="true"><span data-slate-string="true"> to discover more.</span></span></span></div></div>`;

const app = document.querySelector<HTMLDivElement>("#app")!;
const component = document.createElement("rich-text-webcomponent") as any;
component.content = html;
component.readOnly = false;
component.variant = "default";
component.exportHtml = (html: string) => {
    console.log(html);
};
component.customUploadFiles = () => {
    console.log("customUploadFiles");
};
app.appendChild(component);
